Sponsors section prototype
hacksoc-manchester/2017-greatunihack pull request #1
Opened 2017-10-04 14:59 UTC by IvanDonat

I've made a basic layout for the sponsors section. It's far from perfect and could use a lot of fixing but the template is dependent on things like image resolution and such, so I don't know if it's worth the effort of making it look good with these images, just to have to change it afterwards.

2017-10-05 04:45 UTC, MisterDoom commented on index.html
> +						If we want 3 pictures per line, use 3u -->
Good comments. Consider adding them under <!-- Sponsors -->.

2017-10-05 04:50 UTC, MisterDoom commented on index.html
> +						<li><a href="#sponsors" class="scrolly">Sponsors</a>
The list item tag should be closed at the end of each item.

2017-10-05 04:51 UTC, MisterDoom commented on index.html
> +
Electrum sponsor section should be included here.

2017-10-05 04:57 UTC, MisterDoom commented on index.html
> +
Bronze and Partners sponsors section should be included here, in this order.

2017-10-05 05:01 UTC, rignatus requested changes
The section looks pretty good.
As the images were only test images, they should not be added. I have left some comments that should be addressed before merging.

2017-10-06 09:36 UTC, IvanDonat commented
I've modified the sponsors section a bit, this might be a bit better than the last time. Feedback?
I haven't added all the sponsor types yet as there aren't enough images.

Another note:
Sometimes when we put smaller images we can create an empty div of some size to center them, but then it looks bad on xsmall screens. This could be fixed by creating a 0u in the CSS to be used on xsmall screens, as it doesn't exist atm.

I'm not sure if there is a better way to do it with this layout we've got.

2017-10-06 09:38 UTC, IvanDonat commented
Also, maybe if we used icons instead of text for the sponsor type? Or slightly different background shades?

2017-10-06 11:23 UTC, andreimuntean commented
Can you please compress the images to less than 20 kB while maintaining their high quality? And please delete the pictures of companies that aren't sponsoring GUH 2017.

I'd suggest closing this pull request and making a new one with complete changes. This is so HackSoc doesn't pull in all the work in progress commits. But up to you.

2017-10-09 11:24 UTC, closed without merging